proyecto_vehiculos_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehiculo.urls'))
]

vehiculo/urls.py
from django.urls import path
from .views import IndexPageView, vehiculo_view, lista_vehiculos, registro_view, login_view, logout_view

urlpatterns = [
    path("", IndexPageView.as_view(), name="index"),
    path('vehiculo/add', vehiculo_view, name='vehiculo_view'),
    path('vehiculo/list', lista_vehiculos, name='lista_vehiculos'),
    path('registro/', registro_view, name='registro_usuario'),
    path('login/', login_view, name="login_view"),
     path('logout/', logout_view, name="logout_view"),
]

vehiculo/models.py
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone
import datetime 



class Vehiculo(models.Model):
    marca = models.CharField(max_length=20, choices=[
        ["Ford", "Ford"],
        ["Chevrolet", "Chevrolet"],
        ["Fiat", "Fiat"],
        ["Toyota", "Toyota"]
    ], default="Ford")

    modelo = models.CharField(max_length = 100)
    serialCarroseria = models.CharField(max_length = 50)
    serialMotor = models.CharField(max_length = 50)
    categoria = models.CharField(max_length=20, choices=[
        ["Particular", "Particular"],
        ["Transporte", "Transporte"],
        ["Carga", "Carga"]
    ], default="Particular") 
    
    
    fecha_creacion = models.DateTimeField(auto_now_add=True)  
    fecha_update = models.DateTimeField(auto_now=True)
    precio = models.DecimalField(max_digits=10, decimal_places=1)

    class Meta:
        permissions = (
            ("visualizar_catalogo", "Puede visualizar listado"),
            ("add_vehiculomodel", "Puede agregar vehículos"),
        )
        
    def __str__(self):
        return self.serialMotor







    

vehiculo/forms.py
from django import forms
from .models import Vehiculo
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistroUsuarioForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")
   

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = '__all__'

vehiculo/views.py
from tokenize import PseudoExtras
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import TemplateView
from .forms import RegistroUsuarioForm, VehiculoForm
from .models import Vehiculo
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType



class IndexPageView(TemplateView):
    template_name = "index.html"

@permission_required('vehiculo.visualizar_catalogo', raise_exception=True)
def lista_vehiculos(request):
    print("Entrando en la vista lista_vehiculos")
    vehiculos = Vehiculo.objects.all()
    return render(request, 'lista_vehiculos.html', {'vehiculos': vehiculos},  )


@permission_required('vehiculo.add_vehiculomodel', raise_exception=True)
def vehiculo_view(request):
    context = {}

    form = VehiculoForm(request.POST )
    print("Entrando en la vista vehiculo_vista")

    if form.is_valid():
        print("Formulario válido, guardando datos")
        form.save()
        print("Datos guardados en la base de datos")
        return HttpResponseRedirect('/vehiculo/list') 

    context['form'] = form
    return render(request, 'vehiculo.html', context)

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                messages.info(request, f"Iniciaste sesión como: {username}.")
                return HttpResponseRedirect('/')
            else:
                messages.error(request, "Usuario o contraseña inválidos.")
        else:
            messages.error(request, "Usuario o contraseña inválidos.")
    
    form = AuthenticationForm()
    return render(request=request, template_name='login.html', context={"login_form": form})


def registro_view(request):
    if request.method == "POST":
        form = RegistroUsuarioForm(request.POST)
        if form.is_valid():
            content_type = ContentType.objects.get_for_model(Vehiculo)
            visualizar_catalogo = Permission.objects.get(codename='visualizar_catalogo',
            content_type=content_type)
            user = form.save()
            user.user_permissions.add(visualizar_catalogo)
            login(request, user)
            messages.success(request, "Registrado Satisfactoriamente.")
            return HttpResponseRedirect('/')
        else:
            messages.error(request, "Registro inválido. Algunos datos ingresados no son correctos.")
    else:
        form = RegistroUsuarioForm()
    
    return render(request, 'registro_usuario.html', {'RegistroUsuarioForm': form})


def logout_view(request):
    logout(request)
    messages.info(request, "Se ha cerrado la sesión satisfactoriamente.")
    return HttpResponseRedirect('/') 

from django.shortcuts import render

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Catálogo de Vehículos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Vehículos</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Inicio</a>
              </li>              
              {% if user.is_authenticated %}    
              <li class="nav-item">
                <a class="nav-link" href="{% url 'vehiculo_view' %}">Agregar</a>
              </li>
              {% endif %}
              {% if user.is_authenticated %}    
              <li class="nav-item">
                <a class="nav-link" href="{% url 'lista_vehiculos' %}">Listar</a>
              </li>
              {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="/logout">Salir</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Hola, {{user.username}}</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    {% block content %} {% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %} 
<h1>Catalogo de Vehículos</h1>
{% endblock %}

templates/lista_vehiculos.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Listado de Vehículos</title>
</head>
<body>
    {% block content %} 
    <div class="container-fluid">
    <h1>Listado de Vehículos</h1>
    </div>
    <div>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">Marca</th>
              <th scope="col">Modelo</th>
              <th scope="col">Serial Carrocería</th>
              <th scope="col">Seria Motor</th>
              <th scope="col">Categoría</th>
              <th scope="col">Precio</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for vehiculo in vehiculos %}
            <tr>
                <td scope="row">{{ vehiculo.marca }}</td>
                <td>{{ vehiculo.modelo }}</td>
                <td>{{ vehiculo.serialCarroseria }}</td>
                <td>{{ vehiculo.serialMotor }}</td>
                <td>{{ vehiculo.categoria }}</td>
                <td>{{ vehiculo.precio }}</td>
              </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    {% endblock %}
</body>
</html>

templates/login.html
{% extends 'base.html' %} 
{% block content %} 
{% load crispy_forms_tags %}

<div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Si nio tienes una cuenta, registrate en <a href="/registro">, para crear una cuenta</a>.</p>
</div>
{% endblock %}

templates/registro_usuario.html
{% extends 'base.html' %} 
{% block content %} 
{% load crispy_forms_tags %}

<div class="container py-5">
    <h1>Registro</h1>
    <form method="POST">
    {% csrf_token %} {{ RegistroUsuarioForm|crispy }}
    <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">
    Si tienes actualmente una cuenta, inicie su sesión en
    <a href="/login">login</a>
    </p> 
</div>

{% endblock %}

templates/vehiculo.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Agregar Vehículo</title>
<body>
    {% block content %} 

    <div class="container-fluid">
        <h1>Agregar Vehículo</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} {# Esto renderizará todos los campos del formulario automáticamente como párrafos #}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
  
    <!-- <div class="container-fluid">
        <h1>Agregar Vehículo</h1>
        <form  method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_marca">Marca:</label>
                <select class="form-control" name="marca" id="id_marca">
                    {% for marca, _ in form.fields.marca.choices %}
                        <option value="{{ marca }}">{{ marca }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="id_modelo">Modelo:</label>
                <input type="text" class="form-control" name="modelo" id="id_modelo">
            </div>

            <div class="form-group">
                <label for="id_serialCarroceria">Serial de Carrocería:</label>
                <input type="text" class="form-control" name="serialCarroceria" id="id_serialCarroceria">
            </div>

            <div class="form-group">
                <label for="id_serialMotor">Serial de Motor:</label>
                <input type="text" class="form-control" name="serialMotor" id="id_serialMotor">
            </div>

            <div class="form-group">
                <label for="id_categoria">Categoría:</label>
                <select class="form-control" name="categoria" id="id_categoria">
                    {% for categoria, _ in form.fields.categoria.choices %}
                        <option value="{{ categoria }}">{{ categoria }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="id_precio">Precio:</label>
                <input type="text" class="form-control" name="precio" id="id_precio">
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div> -->
    {% endblock %}
</body>
</html>